#!/bin/sh

set -e

cd "$(dirname "$0")/.."

echo "Installing development dependencies..."
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade wheel
python3 -m pip install -r requirements.txt
python3 -m pip install -r requirements-dev.txt
python3 -m pip install -r requirements-test.txt

pre-commit install
